name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  flutter_spinkit: ^5.0.0
  toggle_switch: ^2.0.0
  font_awesome_flutter: ^10.10.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  iconsax_flutter: ^1.0.1
  flutter_persian_calendar: ^0.0.3
  iranbanks: ^0.0.3
  iranian_banks: ^1.2.0
  flutter_localization: ^0.3.3
  carousel_slider: ^5.1.1
  shamsi_date: ^1.1.1
  flutter_linear_datepicker: ^3.0.1
  persian_flutter: ^0.2.0
  flutter_launcher_icons: ^0.14.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/1.png"
#  adaptive_icon_foreground: "assets/icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: indieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
