name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_charts: ^30.2.7
  intl: ^0.20.2
  flutter_form_builder: ^10.2.0
  table_calendar: ^3.2.0
  money2: ^6.0.5
  decimal: ^3.2.4
  http: ^1.5.0
#  connectivity_plus: ^6.1.5
  multi_select_flutter: ^4.1.3
  persian_datetime_picker: ^3.1.1
  shamsi_date: ^1.1.1
  uuid: ^4.4.2
  toggle_switch: ^2.0.0
  font_awesome_flutter: ^10.10.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  gradient_icon: ^2.0.9
  iconsax_flutter: ^1.0.1
  pin_code_fields: ^8.0.1
  persian_number_utility: ^1.1.6
  flutter_persian_calendar: ^0.0.3
  iranbanks: ^0.0.3
  iranian_banks: ^1.2.0
  flutter_localization: ^0.3.3
  downloadsfolder: ^1.2.0
  flutter_linear_datepicker: ^3.0.1
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "fonts/3.png"
  remove_alpha_ios: true
  #  adaptive_icon_foreground: "assets/icon_foreground.png"
#  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  fonts:
    - family: indieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: vazir
      fonts:
        - asset: fonts/Vazirmatn-Bold.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/NotoColorEmoji-Regular.ttf
